name: Build
run-name: Build commit "${{ github.sha }}"

on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build build
        run: docker compose --file envs/ci/build/docker-compose.yml build build

      - name: Run build
        run: docker compose --file envs/ci/build/docker-compose.yml run build
